# Site settings
title: Guilherme Xavier
email: gxferreira@gmail.com
description: Xavier is a web-based and Java system developer
url: gxferreira.github.io
github_username: gxferreira

# Build settings
markdown: kramdown
permalink: pretty
